"""Akshar — a Streamlit learning app powered by Gemma 4.

The learner journey: pick an exam goal (NEB, CEE, or IOE), pick a grade,
subject, and chapter, read the preloaded lesson, then generate an AI summary,
practise with a five-question MCQ quiz, and review flashcards. All AI features
call :mod:`ai_service`, which wraps the official ``google-genai`` SDK.
"""

from __future__ import annotations

import os
import re
from collections.abc import Callable

import streamlit as st

import ai_service
import progress
from ai_service import AIServiceError
from content import (
    ContentError,
    filter_lessons,
    lesson_label,
    lessons_signature,
    load_lessons,
    unique_values,
)

AI_NOTICE = (
    "AI-generated by Gemma 4 · may contain mistakes · always verify with your source."
)
MCQ_COUNT = 5
FLASHCARD_COUNT = 5
ASK_LANGUAGE_OPTIONS = {
    "Auto (match lesson)": None,
    "English": "en",
    "नेपाली (Nepali)": "ne",
}
EXAM_GOALS = ("NEB", "CEE", "IOE")
OPTION_LETTERS = ("A", "B", "C", "D")
GRADE_PATTERN = re.compile(r"Grade\s+(\d+)", re.IGNORECASE)


@st.cache_data(show_spinner=False)
def get_lessons(signature: str) -> list[dict]:
    """Load lessons, re-reading them whenever ``signature`` changes.

    ``signature`` is derived from the lesson file's path and modification
    time, so editing ``data/lessons.json`` invalidates the cache without a
    full app restart.
    """
    return load_lessons()


def get_api_key() -> str | None:
    """Return the Gemma API key from Streamlit secrets or the environment.

    ``GEMINI_API_KEY`` is the primary name; ``GOOGLE_API_KEY`` is accepted as a
    fallback so existing team setups keep working. The key is never logged.
    """
    for name in ("GEMINI_API_KEY", "GOOGLE_API_KEY"):
        try:
            value = st.secrets[name]
            if value:
                return str(value)
        except Exception:
            # No secrets file configured, or the key is absent.
            pass
    for name in ("GEMINI_API_KEY", "GOOGLE_API_KEY"):
        value = os.environ.get(name)
        if value:
            return value
    return None


def require_api_key(api_key: str | None) -> bool:
    """Show a helpful message and return False when no key is configured."""
    if api_key:
        return True
    st.info(
        "Connect with Gemma 4 to get explanations, practice questions, and flashcards. "
        "Add `GEMINI_API_KEY` (or `GOOGLE_API_KEY`) to `.streamlit/secrets.toml` or an environment variable."
    )
    return False


def get_progress() -> dict:
    """Return this session's progress state, creating it on first use."""
    if "progress" not in st.session_state:
        st.session_state["progress"] = progress.new_state()
    return st.session_state["progress"]


def render_ai_notice() -> None:
    st.caption("🤖 " + AI_NOTICE)


def exam_goal_of(track: str) -> str:
    """Map a lesson track such as "NEB Grade 11" to NEB, CEE, or IOE."""
    normalized = track.strip().upper()
    for goal in EXAM_GOALS:
        if normalized.startswith(goal):
            return goal
    return track.strip()


def grade_of(track: str) -> str | None:
    """Return the grade number encoded in a track such as "NEB Grade 11"."""
    match = GRADE_PATTERN.search(track)
    return match.group(1) if match else None


def available_goals(lessons: list[dict]) -> list[str]:
    """Return the exam goals present in the lesson data, in a stable order."""
    found = [
        goal
        for goal in EXAM_GOALS
        if any(exam_goal_of(lesson["track"]) == goal for lesson in lessons)
    ]
    extras: list[str] = []
    for lesson in lessons:
        goal = exam_goal_of(lesson["track"])
        if goal not in EXAM_GOALS and goal not in extras:
            extras.append(goal)
    return found + extras


def render_select(
    label: str,
    options: list[str],
    state_key: str,
    *,
    format_func: Callable[[str], str] | None = None,
) -> str | None:
    """Render a sidebar selectbox whose value always stays one of ``options``.

    The selected value lives in ``st.session_state[state_key]``. If a previous
    selection is no longer valid — for example after the exam goal changes —
    it falls back to the first option.
    """
    if not options:
        st.warning(f"No {label.lower()} options are available for this selection.")
        return None
    if st.session_state.get(state_key) not in options:
        st.session_state[state_key] = options[0]
    kwargs: dict = {}
    if format_func is not None:
        kwargs["format_func"] = format_func
    return st.selectbox(label, options, key=state_key, **kwargs)


def select_lesson(lessons: list[dict]) -> dict | None:
    """Render the sidebar selectors and return the selected lesson, if any."""
    st.header("Study setup")

    goal = render_select("Exam goal", available_goals(lessons), "exam-goal")
    if goal is None:
        return None
    candidates = [lesson for lesson in lessons if exam_goal_of(lesson["track"]) == goal]

    grade_options: list[str] = []
    for lesson in candidates:
        grade = grade_of(lesson["track"])
        if grade and f"Grade {grade}" not in grade_options:
            grade_options.append(f"Grade {grade}")
    grade = render_select("Grade", grade_options, "grade") if grade_options else None
    pool = candidates
    if grade:
        grade_number = GRADE_PATTERN.search(grade).group(1)
        pool = [lesson for lesson in candidates if grade_of(lesson["track"]) == grade_number]

    subject = render_select("Subject", unique_values(pool, "subject"), "subject")
    if subject is None:
        return None
    pool = filter_lessons(pool, subject=subject)

    chapter = render_select("Chapter", unique_values(pool, "topic"), "chapter")
    if chapter is None:
        return None
    pool = filter_lessons(pool, topic=chapter)

    language = render_select(
        "Lesson language",
        [lesson["language"] for lesson in pool],
        "language",
        format_func=lesson_label,
    )
    if language is None:
        return None
    return next((lesson for lesson in pool if lesson["language"] == language), pool[0])


def render_summary_tab(lesson: dict, api_key: str | None) -> None:
    state_key = f"summary::{lesson['id']}"

    if st.button("Generate a summary", key=f"gen-summary::{lesson['id']}"):
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing a summary…"):
                try:
                    st.session_state[state_key] = ai_service.generate_summary(
                        lesson["content"], api_key
                    )
                except AIServiceError as exc:
                    st.error(f"Could not generate a summary: {exc}")

    summary = st.session_state.get(state_key)
    if summary:
        st.markdown(summary)
        if st.button("Regenerate", key=f"regen-summary::{lesson['id']}"):
            st.session_state.pop(state_key, None)
            st.rerun()
        render_ai_notice()
    else:
        st.caption("Generate a summary to see AI-powered highlights.")


def render_practice_tab(lesson: dict, api_key: str | None) -> None:
    gen_key = f"mcq-gen::{lesson['id']}"
    data_key = f"mcqs::{lesson['id']}"
    if gen_key not in st.session_state:
        st.session_state[gen_key] = 0
    generation = st.session_state[gen_key]

    if st.button("Generate practice questions", key=f"gen-mcq::{lesson['id']}"):
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing questions…"):
                try:
                    st.session_state[data_key] = ai_service.generate_mcqs(
                        lesson["content"], api_key, count=MCQ_COUNT
                    )
                    st.session_state[gen_key] = generation + 1
                    st.rerun()
                except AIServiceError as exc:
                    st.error(f"Could not generate questions: {exc}")

    questions = st.session_state.get(data_key)
    if not questions:
        st.caption("Generate questions, choose your answers, then check them.")
        return

    with st.form(key=f"mcq-form::{lesson['id']}::{generation}"):
        selections: dict[int, str] = {}
        for index, question in enumerate(questions, start=1):
            st.markdown(f"**Q{index}. {question['question']}**")
            options = [
                f"{letter}. {question['options'][letter]}" for letter in OPTION_LETTERS
            ]
            choice = st.radio(
                f"Answer for question {index}",
                options,
                key=f"mcq-ans::{lesson['id']}::{generation}::{index}",
                label_visibility="collapsed",
            )
            selections[index] = choice[0]

        submitted = st.form_submit_button("Check answers")

    if submitted:
        score = 0
        correct_map: dict[int, str] = {}
        missed_indices: list[int] = []
        for index, question in enumerate(questions, start=1):
            correct = question["answer"]
            correct_map[index] = correct
            if selections.get(index) == correct:
                score += 1
                st.success(f"Q{index}: Correct. {question['explanation']}")
            else:
                missed_indices.append(index)
                st.error(
                    f"Q{index}: The correct answer is **{correct}**. "
                    f"{question['explanation']}"
                )

        progress.record_attempt(get_progress(), lesson["id"], score, len(questions))
        best = progress.get_lesson_progress(get_progress(), lesson["id"])
        st.info(
            f"Score: {score} / {len(questions)} "
            f"({score/len(questions)*100:.0f}%) · "
            f"Best: {best['best_score']} / {best['best_total']}"
        )

        # Review summary
        if missed_indices:
            with st.expander(f"Review {len(missed_indices)} missed question(s)"):
                for idx in missed_indices:
                    q = questions[idx - 1]
                    answer_letter = q["answer"]
                    st.markdown(f"**Q{idx}: {q['question']}**")
                    st.markdown(
                        f"Correct answer: **{answer_letter}. {q['options'][answer_letter]}**"
                    )
                    st.markdown(f"Explanation: {q['explanation']}")
        else:
            st.balloons()
            st.success("Perfect! You got all questions correct!")

        render_ai_notice()

    render_ai_notice()


def render_flashcards_tab(lesson: dict, api_key: str | None) -> None:
    state_key = f"cards::{lesson['id']}"

    if st.button("Generate flashcards", key=f"gen-fc::{lesson['id']}"):
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing flashcards…"):
                try:
                    st.session_state[state_key] = ai_service.generate_flashcards(
                        lesson["content"], api_key, count=FLASHCARD_COUNT
                    )
                except AIServiceError as exc:
                    st.error(f"Could not generate flashcards: {exc}")

    cards = st.session_state.get(state_key)
    if cards:
        for index, card in enumerate(cards, start=1):
            with st.expander(f"Card {index}: {card['question']}"):
                st.write(card["answer"])
        render_ai_notice()
    else:
        st.caption("Generate flashcards to create quick revision cards.")


def render_ask_tab(lesson: dict, api_key: str | None) -> None:
    state_key = f"chat::{lesson['id']}"
    if state_key not in st.session_state:
        st.session_state[state_key] = []
    history: list[dict] = st.session_state[state_key]

    if not history:
        st.caption(
            "Ask a question about this lesson. Gemma 4 answers using only the "
            "lesson text and says so when the lesson does not cover it."
        )

    for message in history:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    language_label = st.selectbox(
        "Answer language",
        list(ASK_LANGUAGE_OPTIONS),
        key=f"ask-lang::{lesson['id']}",
        help="Choose the language Gemma 4 should reply in.",
    )

    with st.form(key=f"ask-form::{lesson['id']}", clear_on_submit=True):
        question = st.text_input(
            "Your question",
            placeholder="e.g. Why is acceleration inversely proportional to mass?",
        )
        submitted = st.form_submit_button("Ask Gemma 4")

    if submitted:
        if require_api_key(api_key):
            if not question.strip():
                st.warning("Please type a question first.")
            else:
                history.append({"role": "user", "content": question.strip()})
                with st.spinner("Gemma 4 is thinking…"):
                    try:
                        answer = ai_service.ask_question(
                            lesson["content"],
                            question.strip(),
                            api_key,
                            history=history[:-1],
                            language=ASK_LANGUAGE_OPTIONS[language_label],
                        )
                        history.append({"role": "assistant", "content": answer})
                    except AIServiceError as exc:
                        st.error(f"Could not answer: {exc}")
                st.rerun()

    if history:
        if st.button("Clear conversation", key=f"clear-chat::{lesson['id']}"):
            st.session_state[state_key] = []
            st.rerun()
        render_ai_notice()


def main() -> None:
    st.set_page_config(
        page_title="Akshar — Learning Platform for Nepal",
        page_icon="📘",
        layout="centered",
    )

    st.title("Akshar")
    st.caption(
        "Learn → understand → practise, with Nepali/English support and Gemma 4."
    )

    try:
        lessons = get_lessons(lessons_signature())
    except ContentError as exc:
        st.error(f"Could not load lesson content: {exc}")
        st.stop()

    with st.sidebar:
        lesson = select_lesson(lessons)

        st.divider()
        if get_api_key():
            st.success("Gemma 4 API key detected.")
        else:
            st.info(
                "Connect with Gemma 4 to get explanations, practice questions, and flashcards. "
                "Add `GEMINI_API_KEY` (or `GOOGLE_API_KEY`) to `.streamlit/secrets.toml` or your environment."
            )

    if lesson is None:
        st.info("Pick an exam goal, subject, and chapter in the sidebar to open a lesson.")
        return

    st.subheader(lesson["title"])
    st.caption(
        f"{lesson['track']} · {lesson['subject']} · {lesson['topic']} "
        f"· {lesson_label(lesson['language'])}"
    )
    with st.expander("Lesson notes", expanded=True):
        st.write(lesson["content"])
    st.caption("Team-authored study notes for this demo, not official NEB/IOE material.")

    api_key = get_api_key()
    tab_summary, tab_ask, tab_practice, tab_flashcards = st.tabs(
        ["📝 Explain", "💬 Ask", "🎯 Practise", "🧠 Flashcards"]
    )
    with tab_summary:
        render_summary_tab(lesson, api_key)
    with tab_ask:
        render_ask_tab(lesson, api_key)
    with tab_practice:
        render_practice_tab(lesson, api_key)
    with tab_flashcards:
        render_flashcards_tab(lesson, api_key)

    # Render progress after the tabs so the counters reflect any attempt recorded
    # during this run — for example, immediately after the learner checks answers.
    with st.sidebar:
        st.divider()
        st.subheader("Your progress")
        summary = progress.summarize(get_progress())
        st.caption(f"Lessons practised: **{summary['lessons_practised']}**")
        st.caption(f"Practice attempts: **{summary['total_attempts']}**")
        st.caption(f"Average best score: **{summary['average_best_percent']}%**")
        if st.button("Reset progress"):
            st.session_state["progress"] = progress.new_state()
            st.rerun()

    st.divider()
    st.caption("Akshar · Team Nepluro · MIT License")


if __name__ == "__main__":
    main()
