"""Akshar — a Streamlit learning app powered by Gemma 4.

The learner journey: pick an exam goal (NEB, CEE, or IOE), pick a grade,
subject, and chapter, read the preloaded lesson, then generate an AI summary,
ask the assistant a question, practise with a five-question MCQ quiz, and
review flashcards. All AI features call :mod:`ai_service`, which wraps the
official ``google-genai`` SDK.
"""

from __future__ import annotations

import os
import re
from collections.abc import Callable

import streamlit as st

import ai_service
import progress
from ai_service import AIServiceError
from content import (
    ContentError,
    filter_lessons,
    lesson_label,
    lessons_signature,
    load_lessons,
    unique_values,
)

AI_NOTICE = (
    "AI-generated by Gemma 4 · may contain mistakes · always verify with your source."
)
MCQ_COUNT = 5
FLASHCARD_COUNT = 5
ASK_LANGUAGE_OPTIONS = {
    "Auto (match lesson)": None,
    "English": "en",
    "नेपाली (Nepali)": "ne",
}
SUGGESTED_QUESTIONS = (
    "Explain this chapter in simpler terms.",
    "Give a worked example from this lesson.",
    "What should I remember for the exam?",
)
EXAM_GOALS = ("NEB", "CEE", "IOE")
OPTION_LETTERS = ("A", "B", "C", "D")
GRADE_PATTERN = re.compile(r"Grade\s+(\d+)", re.IGNORECASE)

# ---------------------------------------------------------------------------
# Design tokens
# ---------------------------------------------------------------------------

APP_CSS = """
:root {
  --ak-primary: #1f6feb;
  --ak-primary-dark: #1a5fd7;
  --ak-text: #111827;
  --ak-muted: #5b6472;
  --ak-subtle: #f4f7fb;
  --ak-border: #e2e8f0;
  --ak-radius: 10px;
}

html, body { overflow-x: hidden; }

/* Typography: system stack with Devanagari support */
html, body, [class*="css"] {
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Noto Sans",
    "Noto Sans Devanagari", "Mangal", "Kokila", sans-serif;
  color: var(--ak-text);
}

/* Main column: a deliberate, readable width */
.block-container {
  max-width: 44rem !important;
  padding: 2.5rem 1.75rem 4rem !important;
}

h1, h2, h3 { line-height: 1.25; letter-spacing: -0.01em; }

/* Reading typography for lessons, explanations, and chat */
[data-testid="stMarkdownContainer"] p {
  line-height: 1.7;
  margin: 0 0 0.9rem;
}
[data-testid="stMarkdownContainer"] ul,
[data-testid="stMarkdownContainer"] ol {
  margin: 0 0 1rem;
  padding-left: 1.4rem;
}
[data-testid="stMarkdownContainer"] li {
  line-height: 1.65;
  margin-bottom: 0.3rem;
}
[data-testid="stMarkdownContainer"] code {
  background: var(--ak-subtle);
  border: 1px solid var(--ak-border);
  border-radius: 6px;
  padding: 0.1rem 0.35rem;
  font-size: 0.92em;
}
[data-testid="stMarkdownContainer"] pre {
  background: var(--ak-subtle);
  border: 1px solid var(--ak-border);
  border-radius: 8px;
  padding: 0.8rem 1rem;
  overflow-x: auto;
}

/* Buttons: comfortable, consistent touch targets */
[data-testid="stButton"] button {
  min-height: 2.5rem;
  padding: 0.45rem 1rem;
  border-radius: var(--ak-radius);
  border: 1px solid var(--ak-border);
  background: #ffffff;
  color: var(--ak-text);
  font-weight: 600;
  transition: background 120ms ease, border-color 120ms ease;
}
[data-testid="stButton"] button:hover {
  background: var(--ak-subtle);
  border-color: #cbd5e1;
}
[data-testid="stButton"] button[kind="primary"] {
  background: var(--ak-primary);
  border-color: var(--ak-primary);
  color: #ffffff;
}
[data-testid="stButton"] button[kind="primary"]:hover {
  background: var(--ak-primary-dark);
  border-color: var(--ak-primary-dark);
}

/* Visible keyboard focus */
:focus-visible {
  outline: 2px solid var(--ak-primary);
  outline-offset: 2px;
}

/* Selects and radios */
[data-testid="stSelectbox"] div[data-baseweb="select"] {
  border-radius: var(--ak-radius);
}
[data-testid="stRadio"] input[type="radio"] {
  width: 1.05rem;
  height: 1.05rem;
}
[data-testid="stRadio"] label {
  min-height: 2.25rem;
  display: flex;
  align-items: center;
}

/* Tabs */
[data-testid="stTabs"] [data-testid="stTab"] {
  font-weight: 600;
  color: var(--ak-muted);
  padding: 0.5rem 0.75rem;
}
[data-testid="stTabs"] [data-testid="stTab"][aria-selected="true"] {
  color: var(--ak-primary);
  border-bottom: 2px solid var(--ak-primary);
}

/* Alerts, expanders, and chat bubbles */
[data-testid="stAlert"] { border-radius: var(--ak-radius); }
[data-testid="stExpander"] { border-radius: var(--ak-radius); }
[data-testid="stChatMessage"] { border-radius: var(--ak-radius); }

/* Sidebar title */
[data-testid="stSidebar"] h1 { font-size: 1.3rem; margin-bottom: 0.1rem; }

/* Mobile: full-width content with tighter padding */
@media (max-width: 768px) {
  .block-container { padding: 1.25rem 1rem 3rem !important; }
}
@media (max-width: 390px) {
  .block-container { padding: 1rem 0.75rem 2.5rem !important; }
}

/* Respect reduced-motion preferences */
@media (prefers-reduced-motion: reduce) {
  * { transition: none !important; animation: none !important; }
}
"""


def inject_app_css() -> None:
    """Apply the Akshar design tokens once per run."""
    st.markdown(f"<style>{APP_CSS}</style>", unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Data loading, API key, and shared helpers
# ---------------------------------------------------------------------------


@st.cache_data(show_spinner=False)
def get_lessons(signature: str) -> list[dict]:
    """Load lessons, re-reading them whenever ``signature`` changes.

    ``signature`` is derived from the lesson file's path and modification
    time, so editing ``data/lessons.json`` invalidates the cache without a
    full app restart.
    """
    return load_lessons()


def get_api_key() -> str | None:
    """Return the Gemma API key from Streamlit secrets or the environment.

    ``GEMINI_API_KEY`` is the primary name; ``GOOGLE_API_KEY`` is accepted as a
    fallback so existing team setups keep working. The key is never logged.
    """
    for name in ("GEMINI_API_KEY", "GOOGLE_API_KEY"):
        try:
            value = st.secrets[name]
            if value:
                return str(value)
        except Exception:
            # No secrets file configured, or the key is absent.
            pass
    for name in ("GEMINI_API_KEY", "GOOGLE_API_KEY"):
        value = os.environ.get(name)
        if value:
            return value
    return None


def require_api_key(api_key: str | None) -> bool:
    """Show a helpful message and return False when no key is configured."""
    if api_key:
        return True
    st.info(
        "Connect with Gemma 4 to get explanations, practice questions, and flashcards. "
        "Add `GEMINI_API_KEY` (or `GOOGLE_API_KEY`) to `.streamlit/secrets.toml` or an environment variable."
    )
    return False


def get_progress() -> dict:
    """Return this session's progress state, creating it on first use."""
    if "progress" not in st.session_state:
        st.session_state["progress"] = progress.new_state()
    return st.session_state["progress"]


def render_ai_notice() -> None:
    st.caption("🤖 " + AI_NOTICE)


def exam_goal_of(track: str) -> str:
    """Map a lesson track such as "NEB Grade 11" to NEB, CEE, or IOE."""
    normalized = track.strip().upper()
    for goal in EXAM_GOALS:
        if normalized.startswith(goal):
            return goal
    return track.strip()


def grade_of(track: str) -> str | None:
    """Return the grade number encoded in a track such as "NEB Grade 11"."""
    match = GRADE_PATTERN.search(track)
    return match.group(1) if match else None


def available_goals(lessons: list[dict]) -> list[str]:
    """Return the exam goals present in the lesson data, in a stable order."""
    found = [
        goal
        for goal in EXAM_GOALS
        if any(exam_goal_of(lesson["track"]) == goal for lesson in lessons)
    ]
    extras: list[str] = []
    for lesson in lessons:
        goal = exam_goal_of(lesson["track"])
        if goal not in EXAM_GOALS and goal not in extras:
            extras.append(goal)
    return found + extras


def render_select(
    label: str,
    options: list[str],
    state_key: str,
    *,
    format_func: Callable[[str], str] | None = None,
) -> str | None:
    """Render a sidebar selectbox whose value always stays one of ``options``.

    The selected value lives in ``st.session_state[state_key]``. If a previous
    selection is no longer valid — for example after the exam goal changes —
    it falls back to the first option.
    """
    if not options:
        st.warning(f"No {label.lower()} options are available for this selection.")
        return None
    if st.session_state.get(state_key) not in options:
        st.session_state[state_key] = options[0]
    kwargs: dict = {}
    if format_func is not None:
        kwargs["format_func"] = format_func
    return st.selectbox(label, options, key=state_key, **kwargs)


def select_lesson(lessons: list[dict]) -> dict | None:
    """Render the study-setup selectors and return the selected lesson."""
    goal = render_select("Exam goal", available_goals(lessons), "exam-goal")
    if goal is None:
        return None
    candidates = [lesson for lesson in lessons if exam_goal_of(lesson["track"]) == goal]

    grade_options: list[str] = []
    for lesson in candidates:
        grade = grade_of(lesson["track"])
        if grade and f"Grade {grade}" not in grade_options:
            grade_options.append(f"Grade {grade}")
    grade = render_select("Grade", grade_options, "grade") if grade_options else None
    pool = candidates
    if grade:
        grade_number = GRADE_PATTERN.search(grade).group(1)
        pool = [lesson for lesson in candidates if grade_of(lesson["track"]) == grade_number]

    subject = render_select("Subject", unique_values(pool, "subject"), "subject")
    if subject is None:
        return None
    pool = filter_lessons(pool, subject=subject)

    chapter = render_select("Chapter", unique_values(pool, "topic"), "chapter")
    if chapter is None:
        return None
    pool = filter_lessons(pool, topic=chapter)

    language = render_select(
        "Lesson language",
        [lesson["language"] for lesson in pool],
        "language",
        format_func=lesson_label,
    )
    if language is None:
        return None
    return next((lesson for lesson in pool if lesson["language"] == language), pool[0])


def render_sidebar_setup(lessons: list[dict]) -> dict | None:
    """Render the top of the sidebar: app identity and study setup."""
    with st.sidebar:
        st.title("Akshar")
        st.caption("Learning platform for Nepal")
        st.divider()
        st.subheader("Study setup")
        st.caption("Start with an exam goal, then narrow down.")
        return select_lesson(lessons)


def render_progress_section() -> None:
    """Render the bottom of the sidebar: honest, session-scoped progress."""
    with st.sidebar:
        st.divider()
        st.subheader("Your progress")
        summary = progress.summarize(get_progress())
        st.caption(f"Lessons practised: **{summary['lessons_practised']}**")
        st.caption(f"Practice attempts: **{summary['total_attempts']}**")
        st.caption(f"Average best score: **{summary['average_best_percent']}%**")
        if st.button("Reset progress", key="reset-progress"):
            st.session_state["progress"] = progress.new_state()
            st.rerun()
        st.divider()
        if get_api_key():
            st.caption("✓ Gemma 4 connected.")
        else:
            st.caption(
                "Gemma 4 not connected — add `GEMINI_API_KEY` to "
                "`.streamlit/secrets.toml` or your environment for AI features."
            )


# ---------------------------------------------------------------------------
# Lesson reading experience
# ---------------------------------------------------------------------------


def _short_chapter(topic: str, limit: int = 26) -> str:
    """Return a chapter title short enough for a navigation button."""
    return topic if len(topic) <= limit else topic[: limit - 1].rstrip() + "…"


def _select_chapter(topic: str) -> None:
    """Select ``topic`` in the sidebar; the click triggers a rerun."""
    st.session_state["chapter"] = topic


def render_chapter_navigation(lessons: list[dict], lesson: dict) -> None:
    """Offer previous/next buttons for sibling chapters of this lesson."""
    goal = exam_goal_of(lesson["track"])
    grade = grade_of(lesson["track"])
    pool = [item for item in lessons if exam_goal_of(item["track"]) == goal]
    if grade:
        pool = [item for item in pool if grade_of(item["track"]) == grade]
    pool = [item for item in pool if item["subject"] == lesson["subject"]]

    topics = unique_values(pool, "topic")
    if len(topics) < 2 or lesson["topic"] not in topics:
        return
    index = topics.index(lesson["topic"])

    columns = st.columns(2)
    if index > 0:
        previous = topics[index - 1]
        columns[0].button(
            f"← {_short_chapter(previous)}",
            key=f"prev-chapter::{lesson['id']}",
            on_click=_select_chapter,
            args=(previous,),
            help=previous,
        )
    if index < len(topics) - 1:
        following = topics[index + 1]
        columns[1].button(
            f"{_short_chapter(following)} →",
            key=f"next-chapter::{lesson['id']}",
            on_click=_select_chapter,
            args=(following,),
            help=following,
        )


def render_lesson(lesson: dict, lessons: list[dict]) -> None:
    """Render the lesson as the page's main reading content."""
    st.title(lesson["title"])
    st.caption(
        f"{lesson['track']} · {lesson['subject']} · Chapter: {lesson['topic']} "
        f"· {lesson_label(lesson['language'])}"
    )
    st.divider()
    st.markdown(lesson["content"])
    st.caption("Team-authored study notes — not official NEB/CEE/IOE material.")
    st.divider()
    render_chapter_navigation(lessons, lesson)


# ---------------------------------------------------------------------------
# AI summary
# ---------------------------------------------------------------------------


def render_summary_tab(lesson: dict, api_key: str | None) -> None:
    state_key = f"summary::{lesson['id']}"

    if st.button("Generate a summary", key=f"gen-summary::{lesson['id']}"):
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing a summary…"):
                try:
                    st.session_state[state_key] = ai_service.generate_summary(
                        lesson["content"], api_key
                    )
                except AIServiceError as exc:
                    st.error(f"Could not generate a summary: {exc}")

    summary = st.session_state.get(state_key)
    if summary:
        st.markdown(summary)
        if st.button("Regenerate", key=f"regen-summary::{lesson['id']}"):
            st.session_state.pop(state_key, None)
            st.rerun()
        render_ai_notice()
    else:
        st.caption("Generate a summary to see AI-powered highlights.")


# ---------------------------------------------------------------------------
# AI ask tab
# ---------------------------------------------------------------------------


def _prefill_question(input_key: str, suggestion: str) -> None:
    """Put a suggested question into the ask input; the click reruns the app."""
    st.session_state[input_key] = suggestion


def render_ask_tab(lesson: dict, api_key: str | None) -> None:
    state_key = f"chat::{lesson['id']}"
    input_key = f"ask-input::{lesson['id']}"
    if state_key not in st.session_state:
        st.session_state[state_key] = []
    history: list[dict] = st.session_state[state_key]

    if not history:
        st.caption(
            "Ask a question about this lesson. Gemma 4 answers using only the "
            "lesson text and says so when the lesson does not cover it."
        )

    for message in history:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    st.caption("Suggested questions:")
    columns = st.columns(len(SUGGESTED_QUESTIONS))
    for index, suggestion in enumerate(SUGGESTED_QUESTIONS):
        columns[index].button(
            suggestion,
            key=f"suggest::{lesson['id']}::{index}",
            on_click=_prefill_question,
            args=(input_key, suggestion),
        )

    language_label = st.selectbox(
        "Answer language",
        list(ASK_LANGUAGE_OPTIONS),
        key=f"ask-lang::{lesson['id']}",
        help="Choose the language Gemma 4 should reply in.",
    )

    with st.form(key=f"ask-form::{lesson['id']}", clear_on_submit=True):
        question = st.text_input(
            "Your question",
            placeholder="e.g. Why is acceleration inversely proportional to mass?",
            key=input_key,
            help="Press Enter to ask.",
        )
        submitted = st.form_submit_button("Ask Gemma 4", type="primary")

    if submitted:
        if require_api_key(api_key):
            if not question.strip():
                st.warning("Please type a question first.")
            else:
                history.append({"role": "user", "content": question.strip()})
                with st.spinner("Gemma 4 is thinking…"):
                    try:
                        answer = ai_service.ask_question(
                            lesson["content"],
                            question.strip(),
                            api_key,
                            history=history[:-1],
                            language=ASK_LANGUAGE_OPTIONS[language_label],
                        )
                        history.append({"role": "assistant", "content": answer})
                    except AIServiceError as exc:
                        st.error(f"Could not answer: {exc}")
                st.rerun()

    if history:
        if st.button("Clear conversation", key=f"clear-chat::{lesson['id']}"):
            st.session_state[state_key] = []
            st.rerun()
        render_ai_notice()


# ---------------------------------------------------------------------------
# Practice quiz
# ---------------------------------------------------------------------------


def _generate_quiz(lesson: dict, api_key: str | None) -> bool:
    """Fetch ``MCQ_COUNT`` questions from Gemma 4; return True on success."""
    data_key = f"mcqs::{lesson['id']}"
    try:
        questions = ai_service.generate_mcqs(
            lesson["content"], api_key, count=MCQ_COUNT
        )
    except AIServiceError as exc:
        st.error(f"Could not generate questions: {exc}")
        return False
    st.session_state[data_key] = questions
    st.session_state[f"mcq-gen::{lesson['id']}"] += 1
    st.session_state[f"mcq-attempt::{lesson['id']}"] += 1
    st.session_state[f"mcq-checked::{lesson['id']}"] = False
    st.session_state.pop(f"mcq-selections::{lesson['id']}", None)
    return True


def _retry_quiz(lesson_id: str) -> None:
    """Reset the current quiz so the same questions can be answered again."""
    st.session_state[f"mcq-attempt::{lesson_id}"] += 1
    st.session_state[f"mcq-checked::{lesson_id}"] = False
    st.session_state.pop(f"mcq-selections::{lesson_id}", None)


def render_practice_tab(lesson: dict, api_key: str | None) -> None:
    """Five-question MCQ quiz with a focused form and a full results review."""
    gen_key = f"mcq-gen::{lesson['id']}"
    attempt_key = f"mcq-attempt::{lesson['id']}"
    data_key = f"mcqs::{lesson['id']}"
    checked_key = f"mcq-checked::{lesson['id']}"
    st.session_state.setdefault(gen_key, 0)
    st.session_state.setdefault(attempt_key, 0)

    if st.button(
        "Generate practice questions",
        key=f"gen-mcq::{lesson['id']}",
        type="primary",
    ):
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing questions…"):
                _generate_quiz(lesson, api_key)
                st.rerun()

    questions = st.session_state.get(data_key)
    if not questions:
        st.caption("Generate five practice questions, answer them, then check.")
        return

    if not st.session_state.get(checked_key, False):
        _render_quiz_form(lesson, questions, attempt_key, checked_key)
    else:
        selections = st.session_state.get(f"mcq-selections::{lesson['id']}", {})
        _render_quiz_results(lesson, questions, selections)


def _render_quiz_form(
    lesson: dict, questions: list[dict], attempt_key: str, checked_key: str
) -> None:
    """Render the answer form; on submission, hand over to the results view."""
    attempt = st.session_state[attempt_key]
    selections_key = f"mcq-selections::{lesson['id']}"
    st.caption(
        f"{len(questions)} questions · choose one answer per question, "
        "then check your answers."
    )
    with st.form(key=f"mcq-form::{lesson['id']}::{attempt}"):
        selections: dict[int, str] = {}
        for index, question in enumerate(questions, start=1):
            st.markdown(f"**Question {index} of {len(questions)}**")
            st.markdown(question["question"])
            options = [
                f"{letter}. {question['options'][letter]}" for letter in OPTION_LETTERS
            ]
            choice = st.radio(
                f"Answer for question {index}",
                options,
                key=f"mcq-ans::{lesson['id']}::{attempt}::{index}",
                label_visibility="collapsed",
            )
            selections[index] = choice[0]

        submitted = st.form_submit_button("Check answers", type="primary")

    if submitted:
        score = sum(
            1
            for index, question in enumerate(questions, start=1)
            if selections.get(index) == question["answer"]
        )
        st.session_state[selections_key] = selections
        st.session_state[checked_key] = True
        progress.record_attempt(get_progress(), lesson["id"], score, len(questions))
        _render_quiz_results(lesson, questions, selections)


def _render_quiz_results(
    lesson: dict, questions: list[dict], selections: dict[int, str]
) -> None:
    """Show the score, a per-question review, and clear next actions."""
    total = len(questions)
    score = sum(
        1
        for index, question in enumerate(questions, start=1)
        if selections.get(index) == question["answer"]
    )
    incorrect = total - score
    percent = round(score / total * 100)

    st.subheader("Results")
    st.markdown(f"**Score: {score} / {total}** ({percent}%)")
    st.caption(f"{score} correct · {incorrect} incorrect")
    best = progress.get_lesson_progress(get_progress(), lesson["id"])
    if best:
        st.caption(f"Best so far for this lesson: {best['best_score']} / {best['best_total']}")

    if score == total:
        st.success("Perfect score — excellent work!")
    elif score >= total / 2:
        st.success("Good effort — review the explanations below and try again.")
    else:
        st.info("Keep going — reread the lesson, then review the questions below.")

    st.divider()
    st.subheader("Answer review")
    for index, question in enumerate(questions, start=1):
        picked = selections.get(index)
        correct = question["answer"]
        status = "✓ Correct" if picked == correct else "✗ Incorrect"
        st.markdown(f"**Question {index} of {total} — {status}**")
        st.markdown(question["question"])
        option_lines = []
        for letter in OPTION_LETTERS:
            text = question["options"][letter]
            if letter == correct:
                option_lines.append(f"- ✓ **{letter}. {text}** — correct answer")
            elif letter == picked:
                option_lines.append(f"- ✗ {letter}. {text} — your answer")
            else:
                option_lines.append(f"- {letter}. {text}")
        st.markdown("\n".join(option_lines))
        st.markdown(f"*Why:* {question['explanation']}")
        st.divider()

    st.markdown("**Next steps**")
    columns = st.columns(2)
    columns[0].button(
        "Try again",
        key=f"retry-mcq::{lesson['id']}",
        on_click=_retry_quiz,
        args=(lesson["id"],),
        help="Answer the same five questions again.",
    )
    if columns[1].button(
        "New questions",
        key=f"new-mcq::{lesson['id']}",
        help="Generate a fresh set of five questions from this lesson.",
    ):
        api_key = get_api_key()
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing questions…"):
                if _generate_quiz(lesson, api_key):
                    st.rerun()

    render_ai_notice()


# ---------------------------------------------------------------------------
# Flashcards
# ---------------------------------------------------------------------------


def render_flashcards_tab(lesson: dict, api_key: str | None) -> None:
    state_key = f"cards::{lesson['id']}"

    if st.button("Generate flashcards", key=f"gen-fc::{lesson['id']}"):
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing flashcards…"):
                try:
                    st.session_state[state_key] = ai_service.generate_flashcards(
                        lesson["content"], api_key, count=FLASHCARD_COUNT
                    )
                except AIServiceError as exc:
                    st.error(f"Could not generate flashcards: {exc}")

    cards = st.session_state.get(state_key)
    if cards:
        for index, card in enumerate(cards, start=1):
            with st.expander(f"Card {index}: {card['question']}"):
                st.markdown(card["answer"])
        render_ai_notice()
    else:
        st.caption("Generate flashcards to create quick revision cards.")


# ---------------------------------------------------------------------------
# App entry point
# ---------------------------------------------------------------------------


def main() -> None:
    st.set_page_config(
        page_title="Akshar — Learning Platform for Nepal",
        page_icon="📘",
        layout="centered",
    )
    inject_app_css()

    st.caption("**AKSHAR** — Learning platform for Nepal")

    try:
        lessons = get_lessons(lessons_signature())
    except ContentError as exc:
        st.error(f"Could not load lesson content: {exc}")
        st.stop()

    lesson = render_sidebar_setup(lessons)

    if lesson is None:
        st.info("Pick an exam goal, subject, and chapter in the sidebar to open a lesson.")
        return

    render_lesson(lesson, lessons)

    api_key = get_api_key()
    tab_summary, tab_ask, tab_practice, tab_flashcards = st.tabs(
        ["📝 Explain", "💬 Ask", "🎯 Practise", "🧠 Flashcards"]
    )
    with tab_summary:
        render_summary_tab(lesson, api_key)
    with tab_ask:
        render_ask_tab(lesson, api_key)
    with tab_practice:
        render_practice_tab(lesson, api_key)
    with tab_flashcards:
        render_flashcards_tab(lesson, api_key)

    # Rendered after the tabs so counters reflect any attempt recorded
    # during this run — for example, immediately after the learner submits
    # answers.
    render_progress_section()

    st.divider()
    st.caption("Akshar · Team Nepluro · MIT License")


if __name__ == "__main__":
    main()
