"""Akshar — a Streamlit learning app powered by Gemma 4.

Flow: choose a track/topic -> read the lesson -> ask for an explanation,
practise multiple-choice questions, or review flashcards. All AI features call
:mod:`ai_service`, which wraps the official ``google-genai`` SDK.
"""

from __future__ import annotations

import os

import streamlit as st

import ai_service
import progress
from ai_service import AIServiceError
from content import (
    ContentError,
    filter_lessons,
    lesson_label,
    lessons_signature,
    load_lessons,
    unique_values,
)

AI_NOTICE = (
    "AI-generated by Gemma 4 · may contain mistakes · always verify with your source."
)
MCQ_COUNT = 3
FLASHCARD_COUNT = 4


@st.cache_data(show_spinner=False)
def get_lessons(signature: str) -> list[dict]:
    """Load lessons, re-reading them whenever ``signature`` changes.

    ``signature`` is derived from the lesson file's path and modification
    time, so editing ``data/lessons.json`` invalidates the cache without a
    full app restart.
    """
    return load_lessons()


def get_api_key() -> str | None:
    """Return the API key from Streamlit secrets or environment variables."""
    try:
        key = st.secrets["GOOGLE_API_KEY"]
        if key:
            return str(key)
    except Exception:
        # No secrets file configured, or the key is absent.
        pass
    return os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")


def require_api_key(api_key: str | None) -> bool:
    """Show a helpful message and return False when no key is configured."""
    if api_key:
        return True
    st.warning(
        "No Gemma 4 API key found. Add `GOOGLE_API_KEY` to "
        "`.streamlit/secrets.toml` or an environment variable, then reload."
    )
    return False


def get_progress() -> dict:
    """Return this session's progress state, creating it on first use."""
    if "progress" not in st.session_state:
        st.session_state["progress"] = progress.new_state()
    return st.session_state["progress"]


def render_ai_notice() -> None:
    st.caption("🤖 " + AI_NOTICE)


def render_summary_tab(lesson: dict, api_key: str | None) -> None:
    state_key = f"summary::{lesson['id']}"

    if st.button("Generate a summary", key=f"gen-summary::{lesson['id']}"):
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing a summary…"):
                try:
                    st.session_state[state_key] = ai_service.generate_summary(
                        lesson["content"], api_key
                    )
                except AIServiceError as exc:
                    st.error(f"Could not generate a summary: {exc}")

    summary = st.session_state.get(state_key)
    if summary:
        st.markdown(summary)
        render_ai_notice()


def render_practice_tab(lesson: dict, api_key: str | None) -> None:
    gen_key = f"mcq-gen::{lesson['id']}"
    data_key = f"mcqs::{lesson['id']}"
    if gen_key not in st.session_state:
        st.session_state[gen_key] = 0
    generation = st.session_state[gen_key]

    if st.button("Generate practice questions", key=f"gen-mcq::{lesson['id']}"):
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing questions…"):
                try:
                    st.session_state[data_key] = ai_service.generate_mcqs(
                        lesson["content"], api_key, count=MCQ_COUNT
                    )
                    st.session_state[gen_key] = generation + 1
                    st.rerun()
                except AIServiceError as exc:
                    st.error(f"Could not generate questions: {exc}")

    questions = st.session_state.get(data_key)
    if not questions:
        st.caption("Generate questions, choose your answers, then check them.")
        return

    with st.form(key=f"mcq-form::{lesson['id']}::{generation}"):
        selections: dict[int, str] = {}
        for index, question in enumerate(questions, start=1):
            st.markdown(f"**Q{index}. {question['question']}**")
            options = [
                f"{letter}. {question['options'][letter]}"
                for letter in ("A", "B", "C", "D")
            ]
            choice = st.radio(
                f"Answer for question {index}",
                options,
                key=f"mcq-ans::{lesson['id']}::{generation}::{index}",
                label_visibility="collapsed",
            )
            selections[index] = choice[0]

        submitted = st.form_submit_button("Check answers")

    if submitted:
        score = 0
        for index, question in enumerate(questions, start=1):
            correct = question["answer"]
            if selections[index] == correct:
                score += 1
                st.success(f"Q{index}: Correct. {question['explanation']}")
            else:
                st.error(
                    f"Q{index}: The correct answer is **{correct}**. "
                    f"{question['explanation']}"
                )

        progress.record_attempt(get_progress(), lesson["id"], score, len(questions))
        best = progress.get_lesson_progress(get_progress(), lesson["id"])
        st.info(
            f"Score: {score} / {len(questions)} · "
            f"Best: {best['best_score']} / {best['best_total']}"
        )

    render_ai_notice()


def render_flashcards_tab(lesson: dict, api_key: str | None) -> None:
    state_key = f"cards::{lesson['id']}"

    if st.button("Generate flashcards", key=f"gen-fc::{lesson['id']}"):
        if require_api_key(api_key):
            with st.spinner("Gemma 4 is writing flashcards…"):
                try:
                    st.session_state[state_key] = ai_service.generate_flashcards(
                        lesson["content"], api_key, count=FLASHCARD_COUNT
                    )
                except AIServiceError as exc:
                    st.error(f"Could not generate flashcards: {exc}")

    cards = st.session_state.get(state_key)
    if cards:
        for index, card in enumerate(cards, start=1):
            with st.expander(f"Card {index}: {card['question']}"):
                st.write(card["answer"])
        render_ai_notice()


def main() -> None:
    st.set_page_config(
        page_title="Akshar — Learning Platform for Nepal",
        page_icon="📘",
        layout="centered",
    )

    st.title("Akshar")
    st.caption(
        "Learn → understand → practise, with Nepali/English support and Gemma 4."
    )

    try:
        lessons = get_lessons(lessons_signature())
    except ContentError as exc:
        st.error(f"Could not load lesson content: {exc}")
        st.stop()

    with st.sidebar:
        st.header("Study setup")
        track = st.selectbox("Track", unique_values(lessons, "track"))
        subjects = unique_values(filter_lessons(lessons, track=track), "subject")
        subject = st.selectbox("Subject", subjects)
        topics = unique_values(
            filter_lessons(lessons, track=track, subject=subject), "topic"
        )
        topic = st.selectbox("Topic", topics)
        variants = filter_lessons(lessons, track=track, subject=subject, topic=topic)
        languages = unique_values(variants, "language")
        language = st.selectbox("Lesson language", languages, format_func=lesson_label)

        st.divider()
        if get_api_key():
            st.success("Gemma 4 API key detected.")
        else:
            st.warning("No Gemma 4 API key detected.")
            st.caption(
                "Add `GOOGLE_API_KEY` to `.streamlit/secrets.toml` or your environment."
            )

    lesson = next(item for item in variants if item["language"] == language)

    st.subheader(lesson["title"])
    st.caption(
        f"{lesson['track']} · {lesson['subject']} · {lesson['topic']} "
        f"· {lesson_label(lesson['language'])}"
    )
    with st.expander("Lesson notes", expanded=True):
        st.write(lesson["content"])
    st.caption("Team-authored study notes for this demo, not official NEB/IOE material.")

    api_key = get_api_key()
    tab_summary, tab_practice, tab_flashcards = st.tabs(
        ["📝 Explain", "🎯 Practise", "🧠 Flashcards"]
    )
    with tab_summary:
        render_summary_tab(lesson, api_key)
    with tab_practice:
        render_practice_tab(lesson, api_key)
    with tab_flashcards:
        render_flashcards_tab(lesson, api_key)

    # Render progress after the tabs so the counters reflect any attempt recorded
    # during this run — for example, immediately after the learner checks answers.
    with st.sidebar:
        st.divider()
        st.subheader("Your progress")
        summary = progress.summarize(get_progress())
        st.caption(f"Lessons practised: **{summary['lessons_practised']}**")
        st.caption(f"Practice attempts: **{summary['total_attempts']}**")
        st.caption(f"Average best score: **{summary['average_best_percent']}%**")
        if st.button("Reset progress"):
            st.session_state["progress"] = progress.new_state()
            st.rerun()

    st.divider()
    st.caption("Akshar · Team Nepluro · MIT License")


if __name__ == "__main__":
    main()
